import { contextBridge, ipcRenderer } from 'electron'

import { IPC_CHANNELS, type AgentManagerApi, type ManagerEvent, type StartSessionRequest } from '../src/shared/manager-api'

const api: AgentManagerApi = {
  platform: process.platform,
  listSessions: () => ipcRenderer.invoke(IPC_CHANNELS.listSessions),
  terminalReplay: (sessionId) => ipcRenderer.invoke(IPC_CHANNELS.terminalReplay, sessionId),
  listAuditEntries: () => ipcRenderer.invoke(IPC_CHANNELS.listAuditEntries),
  listTokenUsageSummary: (query) => ipcRenderer.invoke(IPC_CHANNELS.listTokenUsageSummary, query),
  listTokenUsageDetails: (query) => ipcRenderer.invoke(IPC_CHANNELS.listTokenUsageDetails, query),
  exportAuditEntries: (entryIds) => ipcRenderer.invoke(IPC_CHANNELS.exportAuditEntries, entryIds),
  startSession: (request: StartSessionRequest) => ipcRenderer.invoke(IPC_CHANNELS.startSession, request),
  write: (sessionId, data) => ipcRenderer.invoke(IPC_CHANNELS.write, sessionId, data),
  resize: (sessionId, cols, rows) => ipcRenderer.invoke(IPC_CHANNELS.resize, sessionId, cols, rows),
  stopSession: (sessionId) => ipcRenderer.invoke(IPC_CHANNELS.stopSession, sessionId),
  restartSession: (sessionId) => ipcRenderer.invoke(IPC_CHANNELS.restartSession, sessionId),
  continueSession: (sessionId) => ipcRenderer.invoke(IPC_CHANNELS.continueSession, sessionId),
  tryRecoveryOnce: (sessionId) => ipcRenderer.invoke(IPC_CHANNELS.tryRecoveryOnce, sessionId),
  acceptRecoverySuggestion: (sessionId) => ipcRenderer.invoke(IPC_CHANNELS.acceptRecoverySuggestion, sessionId),
  dismissRecoverySuggestion: (sessionId) => ipcRenderer.invoke(IPC_CHANNELS.dismissRecoverySuggestion, sessionId),
  removeSession: (sessionId) => ipcRenderer.invoke(IPC_CHANNELS.removeSession, sessionId),
  detachSession: (sessionId) => ipcRenderer.invoke(IPC_CHANNELS.detachSession, sessionId),
  renameSession: (sessionId, displayName) => ipcRenderer.invoke(IPC_CHANNELS.renameSession, sessionId, displayName),
  updateSessionConfig: (sessionId, config) => ipcRenderer.invoke(IPC_CHANNELS.updateSessionConfig, sessionId, config),
  updateSessionProxy: (sessionId, proxy) => ipcRenderer.invoke(IPC_CHANNELS.updateSessionProxy, sessionId, proxy),
  setFullAutoMode: (sessionId, enabled) => ipcRenderer.invoke(IPC_CHANNELS.setFullAutoMode, sessionId, enabled),
  listCCSwitchProviders: (agentKind) => ipcRenderer.invoke(IPC_CHANNELS.listCCSwitchProviders, agentKind),
  getContinueKeywordSettings: () => ipcRenderer.invoke(IPC_CHANNELS.getContinueKeywordSettings),
  updateContinueKeywordSettings: (settings) => ipcRenderer.invoke(IPC_CHANNELS.updateContinueKeywordSettings, settings),
  getSessionSafetySettings: () => ipcRenderer.invoke(IPC_CHANNELS.getSessionSafetySettings),
  updateSessionSafetySettings: (settings) => ipcRenderer.invoke(IPC_CHANNELS.updateSessionSafetySettings, settings),
  getDingTalkSettings: () => ipcRenderer.invoke(IPC_CHANNELS.getDingTalkSettings),
  updateDingTalkSettings: (settings) => ipcRenderer.invoke(IPC_CHANNELS.updateDingTalkSettings, settings),
  resetDingTalkBinding: () => ipcRenderer.invoke(IPC_CHANNELS.resetDingTalkBinding),
  approveSession: (sessionId) => ipcRenderer.invoke(IPC_CHANNELS.approveSession, sessionId),
  listPendingApprovals: () => ipcRenderer.invoke(IPC_CHANNELS.listPendingApprovals),
  approveRequest: (requestId) => ipcRenderer.invoke(IPC_CHANNELS.approveRequest, requestId),
  approveAndRememberRequest: (requestId) => ipcRenderer.invoke(IPC_CHANNELS.approveAndRememberRequest, requestId),
  rejectRequest: (requestId) => ipcRenderer.invoke(IPC_CHANNELS.rejectRequest, requestId),
  approveAllPending: () => ipcRenderer.invoke(IPC_CHANNELS.approveAllPending),
  acceptApprovalSuggestion: (sessionId) => ipcRenderer.invoke(IPC_CHANNELS.acceptApprovalSuggestion, sessionId),
  dismissApprovalSuggestion: (sessionId) => ipcRenderer.invoke(IPC_CHANNELS.dismissApprovalSuggestion, sessionId),
  listApprovalRules: () => ipcRenderer.invoke(IPC_CHANNELS.listApprovalRules),
  addApprovalRule: (command) => ipcRenderer.invoke(IPC_CHANNELS.addApprovalRule, command),
  removeApprovalRule: (command) => ipcRenderer.invoke(IPC_CHANNELS.removeApprovalRule, command),
  listDangerRules: () => ipcRenderer.invoke(IPC_CHANNELS.listDangerRules),
  addDangerRule: (input) => ipcRenderer.invoke(IPC_CHANNELS.addDangerRule, input),
  setDangerRuleEnabled: (ruleId, enabled) => ipcRenderer.invoke(IPC_CHANNELS.setDangerRuleEnabled, ruleId, enabled),
  removeDangerRule: (ruleId) => ipcRenderer.invoke(IPC_CHANNELS.removeDangerRule, ruleId),
  testDangerCommand: (command) => ipcRenderer.invoke(IPC_CHANNELS.testDangerCommand, command),
  getLlmReviewSettings: () => ipcRenderer.invoke(IPC_CHANNELS.getLlmReviewSettings),
  updateLlmReviewSettings: (settings) => ipcRenderer.invoke(IPC_CHANNELS.updateLlmReviewSettings, settings),
  reviewApprovalRules: () => ipcRenderer.invoke(IPC_CHANNELS.reviewApprovalRules),
  chooseWorkspace: () => ipcRenderer.invoke(IPC_CHANNELS.chooseWorkspace),
  chooseExecutable: (agentKind) => ipcRenderer.invoke(IPC_CHANNELS.chooseExecutable, agentKind),
  discoverSessions: (agentKind, workspace) => ipcRenderer.invoke(IPC_CHANNELS.discoverSessions, agentKind, workspace),
  detectAgentEnvironment: (agentKind, executable) => ipcRenderer.invoke(IPC_CHANNELS.detectAgentEnvironment, agentKind, executable),
  installNodeAndNpm: () => ipcRenderer.invoke(IPC_CHANNELS.installNodeAndNpm),
  installAgent: (agentKind, registry) => ipcRenderer.invoke(IPC_CHANNELS.installAgent, agentKind, registry),
  installRipgrep: () => ipcRenderer.invoke(IPC_CHANNELS.installRipgrep),
  readClipboardText: () => ipcRenderer.invoke(IPC_CHANNELS.readClipboardText),
  writeClipboardText: (text) => ipcRenderer.invoke(IPC_CHANNELS.writeClipboardText, text),
  subscribe: (listener) => {
    const handler = (_event: Electron.IpcRendererEvent, message: ManagerEvent): void => listener(message)
    ipcRenderer.on(IPC_CHANNELS.event, handler)
    return () => ipcRenderer.removeListener(IPC_CHANNELS.event, handler)
  },
}

contextBridge.exposeInMainWorld('agentManager', api)
